num1=int(input("Enter the num1="))
num2=int(input("Enter the num2="))
print("\n----------SIMPLE CALCULATOR-------------")
print("Addition=      ",num1+num2)
print("Subtraction=   ",num1-num2)
print("Multiplication=",num1*num2)
print("Division=      ",num1/num2)
